// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgUpdateEventPb } from "./types/iotdepinprotocol/iotdepinprotocol/tx";
import { MsgUpdateKv } from "./types/iotdepinprotocol/iotdepinprotocol/tx";
import { MsgDeleteKv } from "./types/iotdepinprotocol/iotdepinprotocol/tx";
import { MsgCreateDevice } from "./types/iotdepinprotocol/iotdepinprotocol/tx";
import { MsgDeleteDevice } from "./types/iotdepinprotocol/iotdepinprotocol/tx";
import { MsgDeleteEventPb } from "./types/iotdepinprotocol/iotdepinprotocol/tx";
import { MsgCreateEventPb } from "./types/iotdepinprotocol/iotdepinprotocol/tx";
import { MsgUpdateDevice } from "./types/iotdepinprotocol/iotdepinprotocol/tx";
import { MsgCreateKv } from "./types/iotdepinprotocol/iotdepinprotocol/tx";

import { Device as typeDevice } from "./types"
import { EventPb as typeEventPb } from "./types"
import { Kv as typeKv } from "./types"
import { Params as typeParams } from "./types"

export { MsgUpdateEventPb, MsgUpdateKv, MsgDeleteKv, MsgCreateDevice, MsgDeleteDevice, MsgDeleteEventPb, MsgCreateEventPb, MsgUpdateDevice, MsgCreateKv };

type sendMsgUpdateEventPbParams = {
  value: MsgUpdateEventPb,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateKvParams = {
  value: MsgUpdateKv,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeleteKvParams = {
  value: MsgDeleteKv,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateDeviceParams = {
  value: MsgCreateDevice,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeleteDeviceParams = {
  value: MsgDeleteDevice,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeleteEventPbParams = {
  value: MsgDeleteEventPb,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateEventPbParams = {
  value: MsgCreateEventPb,
  fee?: StdFee,
  memo?: string
};

type sendMsgUpdateDeviceParams = {
  value: MsgUpdateDevice,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateKvParams = {
  value: MsgCreateKv,
  fee?: StdFee,
  memo?: string
};


type msgUpdateEventPbParams = {
  value: MsgUpdateEventPb,
};

type msgUpdateKvParams = {
  value: MsgUpdateKv,
};

type msgDeleteKvParams = {
  value: MsgDeleteKv,
};

type msgCreateDeviceParams = {
  value: MsgCreateDevice,
};

type msgDeleteDeviceParams = {
  value: MsgDeleteDevice,
};

type msgDeleteEventPbParams = {
  value: MsgDeleteEventPb,
};

type msgCreateEventPbParams = {
  value: MsgCreateEventPb,
};

type msgUpdateDeviceParams = {
  value: MsgUpdateDevice,
};

type msgCreateKvParams = {
  value: MsgCreateKv,
};


export const registry = new Registry(msgTypes);

type Field = {
  name: string;
  type: unknown;
}
function getStructure(template) {
  const structure: { fields: Field[] } = { fields: [] }
  for (let [key, value] of Object.entries(template)) {
    let field = { name: key, type: typeof value }
    structure.fields.push(field)
  }
  return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
  prefix: string
  signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {

    async sendMsgUpdateEventPb({ value, fee, memo }: sendMsgUpdateEventPbParams): Promise<DeliverTxResponse> {
      if (!signer) {
        throw new Error('TxClient:sendMsgUpdateEventPb: Unable to sign Tx. Signer is not present.')
      }
      try {
        const { address } = (await signer.getAccounts())[0];
        const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, { registry, prefix });
        let msg = this.msgUpdateEventPb({ value: MsgUpdateEventPb.fromPartial(value) })
        return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
      } catch (e: any) {
        throw new Error('TxClient:sendMsgUpdateEventPb: Could not broadcast Tx: ' + e.message)
      }
    },

    async sendMsgUpdateKv({ value, fee, memo }: sendMsgUpdateKvParams): Promise<DeliverTxResponse> {
      if (!signer) {
        throw new Error('TxClient:sendMsgUpdateKv: Unable to sign Tx. Signer is not present.')
      }
      try {
        const { address } = (await signer.getAccounts())[0];
        const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, { registry, prefix });
        let msg = this.msgUpdateKv({ value: MsgUpdateKv.fromPartial(value) })
        return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
      } catch (e: any) {
        throw new Error('TxClient:sendMsgUpdateKv: Could not broadcast Tx: ' + e.message)
      }
    },

    async sendMsgDeleteKv({ value, fee, memo }: sendMsgDeleteKvParams): Promise<DeliverTxResponse> {
      if (!signer) {
        throw new Error('TxClient:sendMsgDeleteKv: Unable to sign Tx. Signer is not present.')
      }
      try {
        const { address } = (await signer.getAccounts())[0];
        const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, { registry, prefix });
        let msg = this.msgDeleteKv({ value: MsgDeleteKv.fromPartial(value) })
        return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
      } catch (e: any) {
        throw new Error('TxClient:sendMsgDeleteKv: Could not broadcast Tx: ' + e.message)
      }
    },

    async sendMsgCreateDevice({ value, fee, memo }: sendMsgCreateDeviceParams): Promise<DeliverTxResponse> {
      if (!signer) {
        throw new Error('TxClient:sendMsgCreateDevice: Unable to sign Tx. Signer is not present.')
      }
      try {
        const { address } = (await signer.getAccounts())[0];
        const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, { registry, prefix });
        let msg = this.msgCreateDevice({ value: MsgCreateDevice.fromPartial(value) })
        return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
      } catch (e: any) {
        throw new Error('TxClient:sendMsgCreateDevice: Could not broadcast Tx: ' + e.message)
      }
    },

    async sendMsgDeleteDevice({ value, fee, memo }: sendMsgDeleteDeviceParams): Promise<DeliverTxResponse> {
      if (!signer) {
        throw new Error('TxClient:sendMsgDeleteDevice: Unable to sign Tx. Signer is not present.')
      }
      try {
        const { address } = (await signer.getAccounts())[0];
        const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, { registry, prefix });
        let msg = this.msgDeleteDevice({ value: MsgDeleteDevice.fromPartial(value) })
        return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
      } catch (e: any) {
        throw new Error('TxClient:sendMsgDeleteDevice: Could not broadcast Tx: ' + e.message)
      }
    },

    async sendMsgDeleteEventPb({ value, fee, memo }: sendMsgDeleteEventPbParams): Promise<DeliverTxResponse> {
      if (!signer) {
        throw new Error('TxClient:sendMsgDeleteEventPb: Unable to sign Tx. Signer is not present.')
      }
      try {
        const { address } = (await signer.getAccounts())[0];
        const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, { registry, prefix });
        let msg = this.msgDeleteEventPb({ value: MsgDeleteEventPb.fromPartial(value) })
        return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
      } catch (e: any) {
        throw new Error('TxClient:sendMsgDeleteEventPb: Could not broadcast Tx: ' + e.message)
      }
    },

    async sendMsgCreateEventPb({ value, fee, memo }: sendMsgCreateEventPbParams): Promise<DeliverTxResponse> {
      if (!signer) {
        throw new Error('TxClient:sendMsgCreateEventPb: Unable to sign Tx. Signer is not present.')
      }
      try {
        const { address } = (await signer.getAccounts())[0];
        const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, { registry, prefix });
        let msg = this.msgCreateEventPb({ value: MsgCreateEventPb.fromPartial(value) })
        return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
      } catch (e: any) {
        throw new Error('TxClient:sendMsgCreateEventPb: Could not broadcast Tx: ' + e.message)
      }
    },

    async sendMsgUpdateDevice({ value, fee, memo }: sendMsgUpdateDeviceParams): Promise<DeliverTxResponse> {
      if (!signer) {
        throw new Error('TxClient:sendMsgUpdateDevice: Unable to sign Tx. Signer is not present.')
      }
      try {
        const { address } = (await signer.getAccounts())[0];
        const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, { registry, prefix });
        let msg = this.msgUpdateDevice({ value: MsgUpdateDevice.fromPartial(value) })
        return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
      } catch (e: any) {
        throw new Error('TxClient:sendMsgUpdateDevice: Could not broadcast Tx: ' + e.message)
      }
    },

    async sendMsgCreateKv({ value, fee, memo }: sendMsgCreateKvParams): Promise<DeliverTxResponse> {
      if (!signer) {
        throw new Error('TxClient:sendMsgCreateKv: Unable to sign Tx. Signer is not present.')
      }
      try {
        const { address } = (await signer.getAccounts())[0];
        const signingClient = await SigningStargateClient.connectWithSigner(addr, signer, { registry, prefix });
        let msg = this.msgCreateKv({ value: MsgCreateKv.fromPartial(value) })
        return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
      } catch (e: any) {
        throw new Error('TxClient:sendMsgCreateKv: Could not broadcast Tx: ' + e.message)
      }
    },


    msgUpdateEventPb({ value }: msgUpdateEventPbParams): EncodeObject {
      try {
        return { typeUrl: "/stccommunity.iotdepinprotocol.iotdepinprotocol.MsgUpdateEventPb", value: MsgUpdateEventPb.fromPartial(value) }
      } catch (e: any) {
        throw new Error('TxClient:MsgUpdateEventPb: Could not create message: ' + e.message)
      }
    },

    msgUpdateKv({ value }: msgUpdateKvParams): EncodeObject {
      try {
        return { typeUrl: "/stccommunity.iotdepinprotocol.iotdepinprotocol.MsgUpdateKv", value: MsgUpdateKv.fromPartial(value) }
      } catch (e: any) {
        throw new Error('TxClient:MsgUpdateKv: Could not create message: ' + e.message)
      }
    },

    msgDeleteKv({ value }: msgDeleteKvParams): EncodeObject {
      try {
        return { typeUrl: "/stccommunity.iotdepinprotocol.iotdepinprotocol.MsgDeleteKv", value: MsgDeleteKv.fromPartial(value) }
      } catch (e: any) {
        throw new Error('TxClient:MsgDeleteKv: Could not create message: ' + e.message)
      }
    },

    msgCreateDevice({ value }: msgCreateDeviceParams): EncodeObject {
      try {
        return { typeUrl: "/stccommunity.iotdepinprotocol.iotdepinprotocol.MsgCreateDevice", value: MsgCreateDevice.fromPartial(value) }
      } catch (e: any) {
        throw new Error('TxClient:MsgCreateDevice: Could not create message: ' + e.message)
      }
    },

    msgDeleteDevice({ value }: msgDeleteDeviceParams): EncodeObject {
      try {
        return { typeUrl: "/stccommunity.iotdepinprotocol.iotdepinprotocol.MsgDeleteDevice", value: MsgDeleteDevice.fromPartial(value) }
      } catch (e: any) {
        throw new Error('TxClient:MsgDeleteDevice: Could not create message: ' + e.message)
      }
    },

    msgDeleteEventPb({ value }: msgDeleteEventPbParams): EncodeObject {
      try {
        return { typeUrl: "/stccommunity.iotdepinprotocol.iotdepinprotocol.MsgDeleteEventPb", value: MsgDeleteEventPb.fromPartial(value) }
      } catch (e: any) {
        throw new Error('TxClient:MsgDeleteEventPb: Could not create message: ' + e.message)
      }
    },

    msgCreateEventPb({ value }: msgCreateEventPbParams): EncodeObject {
      try {
        return { typeUrl: "/stccommunity.iotdepinprotocol.iotdepinprotocol.MsgCreateEventPb", value: MsgCreateEventPb.fromPartial(value) }
      } catch (e: any) {
        throw new Error('TxClient:MsgCreateEventPb: Could not create message: ' + e.message)
      }
    },

    msgUpdateDevice({ value }: msgUpdateDeviceParams): EncodeObject {
      try {
        return { typeUrl: "/stccommunity.iotdepinprotocol.iotdepinprotocol.MsgUpdateDevice", value: MsgUpdateDevice.fromPartial(value) }
      } catch (e: any) {
        throw new Error('TxClient:MsgUpdateDevice: Could not create message: ' + e.message)
      }
    },

    msgCreateKv({ value }: msgCreateKvParams): EncodeObject {
      try {
        return { typeUrl: "/stccommunity.iotdepinprotocol.iotdepinprotocol.MsgCreateKv", value: MsgCreateKv.fromPartial(value) }
      } catch (e: any) {
        throw new Error('TxClient:MsgCreateKv: Could not create message: ' + e.message)
      }
    },

  }
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
  public query: ReturnType<typeof queryClient>;
  public tx: ReturnType<typeof txClient>;
  public structure: Record<string, unknown>;
  public registry: Array<[string, GeneratedType]> = [];

  constructor(client: IgniteClient) {

    this.query = queryClient({ addr: client.env.apiURL });
    this.updateTX(client);
    this.structure = {
      Device: getStructure(typeDevice.fromPartial({})),
      EventPb: getStructure(typeEventPb.fromPartial({})),
      Kv: getStructure(typeKv.fromPartial({})),
      Params: getStructure(typeParams.fromPartial({})),

    };
    client.on('signer-changed', (signer) => {
      this.updateTX(client);
    })
  }
  updateTX(client: IgniteClient) {
    const methods = txClient({
      signer: client.signer,
      addr: client.env.rpcURL,
      prefix: client.env.prefix ?? "cosmos",
    })

    this.tx = methods;
    for (let m in methods) {
      this.tx[m] = methods[m].bind(this.tx);
    }
  }
};

const Module = (test: IgniteClient) => {
  return {
    module: {
      StccommunityIotdepinprotocolIotdepinprotocol: new SDKModule(test)
    },
    registry: msgTypes
  }
}
export default Module;
